version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/banking-frontend/banking-angular
    steps:
      - checkout:
          path: ~/banking-frontend
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY
      - setup_remote_docker      
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules" 
      - run: npm run build-prod
      - run: docker build -t banking-frontend .
      - run: docker tag banking-frontend lahur.ddns.net:5000/banking-frontend:$CIRCLE_BUILD_NUM
      - run: docker tag banking-frontend lahur.ddns.net:5000/banking-frontend:latest
      - run: docker push lahur.ddns.net:5000/banking-frontend:$CIRCLE_BUILD_NUM
      - run: docker push lahur.ddns.net:5000/banking-frontend:latest